/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author DELL
 */
public class BookingTicket extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingTicket.class.getName());

    /**
     * Creates new form Test
     */
    public BookingTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        ticketDetails = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        movieName = new javax.swing.JLabel();
        confirmBooking = new javax.swing.JButton();
        theaterName = new javax.swing.JLabel();
        seatsNumber = new javax.swing.JLabel();
        totalSeats = new javax.swing.JLabel();
        totalPayingAmount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        seatPrice = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ticketDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ticketDetails.setText("Ticket Details");
        getContentPane().add(ticketDetails);
        ticketDetails.setBounds(80, 50, 140, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Movie");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 70, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Seats No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 80, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Total Seats");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 200, 70, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Your Total Bill");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 250, 120, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Total Paying Amount");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 290, 150, 20);

        movieName.setText("Tere Ishq Mein");
        getContentPane().add(movieName);
        movieName.setBounds(280, 80, 170, 30);

        confirmBooking.setBackground(new java.awt.Color(153, 204, 255));
        confirmBooking.setText("Confirm");
        getContentPane().add(confirmBooking);
        confirmBooking.setBounds(140, 370, 160, 23);
        getContentPane().add(theaterName);
        theaterName.setBounds(310, 0, 170, 30);

        seatsNumber.setText("A1");
        getContentPane().add(seatsNumber);
        seatsNumber.setBounds(280, 120, 170, 30);

        totalSeats.setText("2");
        getContentPane().add(totalSeats);
        totalSeats.setBounds(280, 200, 170, 30);

        totalPayingAmount.setText("400");
        getContentPane().add(totalPayingAmount);
        totalPayingAmount.setBounds(280, 290, 170, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Seat Price");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 160, 80, 30);

        seatPrice.setText("200");
        getContentPane().add(seatPrice);
        seatPrice.setBounds(280, 160, 170, 30);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACK.png"))); // NOI18N
        getContentPane().add(backButton);
        backButton.setBounds(10, 10, 26, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/957e753c-f7e4-4237-bdc2-3fae77e7ac3d.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 490, 460);

        setBounds(0, 0, 497, 468);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingTicket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton confirmBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel movieName;
    private javax.swing.JLabel seatPrice;
    private javax.swing.JLabel seatsNumber;
    private javax.swing.JLabel theaterName;
    private javax.swing.JLabel ticketDetails;
    private javax.swing.JLabel totalPayingAmount;
    private javax.swing.JLabel totalSeats;
    // End of variables declaration//GEN-END:variables
public void setTotalPayment(double TotalPayment) {
    totalPayingAmount.setText(String.valueOf(TotalPayment));
}

public javax.swing.JButton getConfirmButton() {
    return confirmBooking;
}

public javax.swing.JLabel getMovie() {
    return movieName;
}

public javax.swing.JLabel getTheaterName() {
    return theaterName;
}

public javax.swing.JLabel getSeats() {
    return seatsNumber;
}

public javax.swing.JLabel getSeatsPrice() {
    return seatPrice;
}
public javax.swing.JLabel getTotalSeats() {
    return totalSeats;
}

public javax.swing.JLabel getTotalPayingAmount() {
    return totalPayingAmount;
}


public void getBackButton(ActionListener l){
    backButton.addActionListener(l);   
}

public void getConfirmBooking(ActionListener l){
    confirmBooking.addActionListener(l);
}

}

