/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author suman
 */
public class comingsoon extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(comingsoon.class.getName());

    /**
     * Creates new form comingsoon
     */
    public comingsoon() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatarMovie = new javax.swing.JButton();
        anacondaMovie = new javax.swing.JButton();
        nowshowing = new javax.swing.JButton();
        indreniMovie = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1314, 930));
        getContentPane().setLayout(null);

        avatarMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        avatarMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Avatarfinal.png"))); // NOI18N
        avatarMovie.setText("Avatar");
        avatarMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        avatarMovie.setVerifyInputWhenFocusTarget(false);
        avatarMovie.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        avatarMovie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        avatarMovie.addActionListener(this::avatarMovieActionPerformed);
        getContentPane().add(avatarMovie);
        avatarMovie.setBounds(80, 80, 280, 570);

        anacondaMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        anacondaMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anoconda.png"))); // NOI18N
        anacondaMovie.setText("Anoconda");
        anacondaMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        anacondaMovie.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        anacondaMovie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        anacondaMovie.addActionListener(this::anacondaMovieActionPerformed);
        getContentPane().add(anacondaMovie);
        anacondaMovie.setBounds(440, 80, 390, 560);

        nowshowing.setText("Now Showing");
        nowshowing.addActionListener(this::nowshowingActionPerformed);
        getContentPane().add(nowshowing);
        nowshowing.setBounds(440, 20, 120, 23);

        indreniMovie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        indreniMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/indreni.png"))); // NOI18N
        indreniMovie.setText("Indreni");
        indreniMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        indreniMovie.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        indreniMovie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        indreniMovie.addActionListener(this::indreniMovieActionPerformed);
        getContentPane().add(indreniMovie);
        indreniMovie.setBounds(920, 80, 330, 560);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finalback.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1500, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1500, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1500, 1080));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1550, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avatarMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatarMovieActionPerformed
        // TODO add your handling code here:
        ((javax.swing.JButton)evt.getSource()).setEnabled(false);
        System.out.println("comingsoon: opening Avatar_summary");
        this.dispose();
        Avatar_summary avatar=new Avatar_summary();
        avatar.setVisible(true);
    }//GEN-LAST:event_avatarMovieActionPerformed

    private void nowshowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowshowingActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TheaterView nowshowing = new TheaterView();
        nowshowing.setVisible(true);
        
    }//GEN-LAST:event_nowshowingActionPerformed

    private void anacondaMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anacondaMovieActionPerformed
        // TODO add your handling code here:
        ((javax.swing.JButton)evt.getSource()).setEnabled(false);
        System.out.println("comingsoon: opening anaconda_summary");
        this.dispose();
        anaconda_summary anaconda=new anaconda_summary();
        anaconda.setVisible(true);
    }//GEN-LAST:event_anacondaMovieActionPerformed

    private void indreniMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indreniMovieActionPerformed
        // TODO add your handling code here:
        ((javax.swing.JButton)evt.getSource()).setEnabled(false);
        System.out.println("comingsoon: opening JhariPachhiKoIndreni_summary");
        this.dispose();
        JhariPachhiKoIndreni_summary jhari=new JhariPachhiKoIndreni_summary();
        jhari.setVisible(true);
        
               
    }//GEN-LAST:event_indreniMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new comingsoon().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anacondaMovie;
    private javax.swing.JButton avatarMovie;
    private javax.swing.JButton indreniMovie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nowshowing;
    // End of variables declaration//GEN-END:variables
}
