/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author HP
 */
public class dhurandar_summary extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dhurandar_summary.class.getName());

    /**
     * Creates new form movie_summary
     */
    public dhurandar_summary() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dhurandar.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 30, 310, 390);

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel3.setText("NOW SHOWING");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 410, 180, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setText("Dhurandhar (2025)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 450, 170, 50);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Dhurandhar is a star-studded saga inspired by incredible true events set in the gritty criminal vein of underworld \nwith a backdrop of Indian patriotism, featuring action sequences, Shakespearean betrayals, and tradecrafts of\n espionage\n\nLanguage:\nGenre: Action, Drama\nCast: Ranveer Singh Sanjay DuttAkshya Khanna\nDirector: Aditya Dhar");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 490, 510, 120);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACK.png"))); // NOI18N
        getContentPane().add(backBtn);
        backBtn.setBounds(10, 10, 26, 30);

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setText("Seat Selection");
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 460, 210, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACKGROUND_PAGE.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 720);

        setBounds(0, 0, 703, 650);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dhurandar_summary().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void seatSelectionActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("dhurandar_summary: opening SeatSelection");
        SeatSelection seat = new SeatSelection(this.jLabel4.getText(), "");
        seat.setVisible(true);
        this.dispose();
    }

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("dhurandar_summary: going back to TheaterView");
        TheaterView view = new TheaterView();
        controller.TheaterController controller = new controller.TheaterController(view);
        controller.open();
        this.dispose();
    }
}
