/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ResetPasswordController;
import javax.swing.JOptionPane;

/**
 *
 * @author salaj
 */
public class Reset_Password extends javax.swing.JFrame {
    private String email;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reset_Password.class.getName());

    /**
     * Creates new form Reset_Password
     */
    public Reset_Password(String email) {
        this.email = email;
        initComponents();
    }
    
    public Reset_Password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NewPassword = new javax.swing.JTextField();
        ConfirmNewPassword = new javax.swing.JTextField();
        Continue = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("RESET");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 60, 70, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 90, 140, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("New Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 160, 130, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel5.setText("Confirm New Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 210, 160, 16);
        getContentPane().add(NewPassword);
        NewPassword.setBounds(320, 180, 150, 22);

        ConfirmNewPassword.addActionListener(this::ConfirmNewPasswordActionPerformed);
        getContentPane().add(ConfirmNewPassword);
        ConfirmNewPassword.setBounds(320, 230, 150, 22);

        Continue.setBackground(new java.awt.Color(255, 102, 0));
        Continue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Continue.setForeground(new java.awt.Color(255, 255, 255));
        Continue.setText("CONTINUE");
        Continue.addActionListener(this::ContinueActionPerformed);
        getContentPane().add(Continue);
        Continue.setBounds(320, 260, 110, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frame.png"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 400);

        setBounds(0, 0, 566, 404);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmNewPasswordActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reset_Password().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConfirmNewPassword;
    private javax.swing.JButton Continue;
    private javax.swing.JTextField NewPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {                                         

    String newPass = NewPassword.getText();
    String confirmPass = ConfirmNewPassword.getText();

    if (!newPass.equals(confirmPass)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match!");
        return;
    }

    ResetPasswordController controller = new ResetPasswordController();
    boolean success = controller.resetPassword(email, newPass);

    if (success) {
        JOptionPane.showMessageDialog(this, "Password updated successfully!");
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Error updating password.");
    }
}
}
