package view;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.stream.Collectors;



public class SeatSelection extends javax.swing.JFrame {
    private final ArrayList<JButton> seats = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SeatSelection.class.getName());

    /**
     * Creates new form SeatSelections
     */
    public SeatSelection() {
        initComponents(); //buttons are created
        setLocationRelativeTo(null);
        
        seats.add(A1);
        seats.add(A2);
        seats.add(A3);
        seats.add(A4);
        seats.add(A5);
        seats.add(A6);
        seats.add(A7);

        seats.add(B1);
        seats.add(B2);
        seats.add(B3);
        seats.add(B4);
        seats.add(B5);
        seats.add(B6);
        seats.add(B7);

        seats.add(C1);
        seats.add(C2);
        seats.add(C3);
        seats.add(C4);
        seats.add(C5);
        seats.add(C6);
        seats.add(C7);

        seats.add(D1);
        seats.add(D2);
        seats.add(D3);
        seats.add(D4);
        seats.add(D5);
        seats.add(D6);
        seats.add(D7);

        seats.add(E1);
        seats.add(E2);
        seats.add(E3);
        seats.add(E4);
        seats.add(E5);
        seats.add(E6);
        seats.add(E7);

        
        seats.add(F1);
        seats.add(F2);
        seats.add(F3);
        seats.add(F4);
        seats.add(F5);
        seats.add(F6);
        seats.add(F7);

       
        
    }

    private String movie;
    private String showTime;
    private final int seatPrice = 200;

    public SeatSelection(String movie, String showTime) {
        this();
        this.movie = movie;
        this.showTime = showTime;
        this.movieLabel.setText(movie);
        this.dateTime.setText(showTime);
        initSeatStates();
        attachSeatListeners();
        attachBuyListener();
    }

    private void initSeatStates() {
        for (JButton b : seats) {
            b.putClientProperty("state", "AVAILABLE");
            b.setBackground(Color.WHITE);
        }
        totalAmount.setText("0");
    }

    private void attachSeatListeners() {
        for (JButton b : seats) {
            b.addActionListener(evt -> {
                // make handler idempotent for rapid clicks
                b.setEnabled(false);
                String state = (String) b.getClientProperty("state");
                if (state == null) state = "AVAILABLE";
                switch (state) {
                    case "AVAILABLE":
                        b.putClientProperty("state", "SELECTED");
                        b.setBackground(Color.YELLOW);
                        break;
                    case "SELECTED":
                        b.putClientProperty("state", "AVAILABLE");
                        b.setBackground(Color.WHITE);
                        break;
                    default:
                        // RESERVED or SOLD -> do nothing
                        break;
                }
                updateTotal();
                b.setEnabled(true);
            });
        }
    }

    private void updateTotal() {
        long count = seats.stream()
                .filter(b -> "SELECTED".equals(b.getClientProperty("state")))
                .count();
        totalAmount.setText(String.valueOf(count * seatPrice));
    }

    private void attachBuyListener() {
        buyTicket.addActionListener(e -> {
            // collect selected seats
            String seatsSelected = seats.stream()
                    .filter(b -> "SELECTED".equals(b.getClientProperty("state")))
                    .map(b -> b.getText())
                    .collect(Collectors.joining(","));
            String total = totalAmount.getText();
            // open BookingTicket and pass data
            BookingTicket booking = new BookingTicket(movie, seatsSelected, String.valueOf(seatPrice),
                    String.valueOf(seatsSelected.isEmpty() ? 0 : seatsSelected.split(",").length), java.time.LocalDateTime.now().toString(), showTime, total);
            booking.setVisible(true);
            this.dispose();
        });
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        cinemaLocation = new javax.swing.JLabel();
        movieLabel = new javax.swing.JLabel();
        dateTime = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        whiteColor = new javax.swing.JTextField();
        available = new javax.swing.JLabel();
        yellowColor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        soldColor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        greyColor = new javax.swing.JTextField();
        sold = new javax.swing.JLabel();
        buyTicket = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        frame = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        jButton5.setText("jButton5");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(589, 570));
        setResizable(false);
        getContentPane().setLayout(null);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACK.png"))); // NOI18N
        backBtn.addActionListener(this::backBtnActionPerformed);
        getContentPane().add(backBtn);
        backBtn.setBounds(10, 10, 30, 30);

        cinemaLocation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cinemaLocation.setText("Baneshwor");
        getContentPane().add(cinemaLocation);
        cinemaLocation.setBounds(40, 90, 70, 16);

        movieLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        movieLabel.setText("Tere ishq mein");
        getContentPane().add(movieLabel);
        movieLabel.setBounds(30, 70, 330, 16);

        dateTime.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        dateTime.setText("Wed 10 December | 01:45 PM");
        getContentPane().add(dateTime);
        dateTime.setBounds(30, 110, 170, 14);

        A.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        A.setText("A");
        getContentPane().add(A);
        A.setBounds(30, 200, 20, 16);

        B.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        B.setText("B");
        getContentPane().add(B);
        B.setBounds(30, 230, 37, 16);

        C.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        C.setText("C");
        getContentPane().add(C);
        C.setBounds(30, 260, 37, 16);

        D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        D.setText("D");
        getContentPane().add(D);
        D.setBounds(30, 290, 20, 20);

        E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        E.setText("E");
        getContentPane().add(E);
        E.setBounds(30, 320, 20, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("F");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 350, 37, 16);

        A1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        A1.setText("A1");
        A1.addActionListener(this::A1ActionPerformed);
        getContentPane().add(A1);
        A1.setBounds(60, 200, 50, 23);

        A2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        A2.setText("A2");
        getContentPane().add(A2);
        A2.setBounds(120, 200, 50, 23);

        A3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        A3.setText("A3");
        getContentPane().add(A3);
        A3.setBounds(180, 200, 50, 23);

        A4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        A4.setText("A4");
        getContentPane().add(A4);
        A4.setBounds(240, 200, 50, 23);

        A5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        A5.setText("A5");
        getContentPane().add(A5);
        A5.setBounds(300, 200, 50, 23);

        A6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        A6.setText("A6");
        getContentPane().add(A6);
        A6.setBounds(360, 200, 50, 23);

        A7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        A7.setText("A7");
        getContentPane().add(A7);
        A7.setBounds(420, 200, 50, 23);

        B1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        B1.setText("B1");
        getContentPane().add(B1);
        B1.setBounds(60, 230, 50, 23);

        B2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        B2.setText("B2");
        getContentPane().add(B2);
        B2.setBounds(120, 230, 50, 23);

        B3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        B3.setText("B3");
        getContentPane().add(B3);
        B3.setBounds(180, 230, 50, 23);

        B4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        B4.setText("B4");
        getContentPane().add(B4);
        B4.setBounds(240, 230, 50, 23);

        B5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        B5.setText("B5");
        getContentPane().add(B5);
        B5.setBounds(300, 230, 50, 23);

        B6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        B6.setText("B6");
        getContentPane().add(B6);
        B6.setBounds(360, 230, 50, 23);

        B7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        B7.setText("B7");
        getContentPane().add(B7);
        B7.setBounds(420, 230, 50, 23);

        C1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        C1.setText("C1");
        getContentPane().add(C1);
        C1.setBounds(60, 260, 50, 23);

        C2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        C2.setText("C2");
        getContentPane().add(C2);
        C2.setBounds(120, 260, 50, 23);

        C3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        C3.setText("C3");
        getContentPane().add(C3);
        C3.setBounds(180, 260, 50, 23);

        C4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        C4.setText("C4");
        getContentPane().add(C4);
        C4.setBounds(240, 260, 50, 23);

        C5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        C5.setText("C5");
        getContentPane().add(C5);
        C5.setBounds(300, 260, 50, 23);

        C6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        C6.setText("C6");
        getContentPane().add(C6);
        C6.setBounds(360, 260, 50, 23);

        C7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        C7.setText("C7");
        getContentPane().add(C7);
        C7.setBounds(420, 260, 50, 23);

        D1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        D1.setText("D1");
        getContentPane().add(D1);
        D1.setBounds(60, 290, 50, 23);

        D2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        D2.setText("D2");
        getContentPane().add(D2);
        D2.setBounds(120, 290, 50, 23);

        D3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        D3.setText("D3");
        getContentPane().add(D3);
        D3.setBounds(180, 290, 50, 23);

        D4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        D4.setText("D4");
        getContentPane().add(D4);
        D4.setBounds(240, 290, 50, 23);

        D5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        D5.setText("D5");
        getContentPane().add(D5);
        D5.setBounds(300, 290, 50, 23);

        D6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        D6.setText("D6");
        getContentPane().add(D6);
        D6.setBounds(360, 290, 50, 23);

        D7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        D7.setText("D7");
        getContentPane().add(D7);
        D7.setBounds(420, 290, 50, 23);

        E1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        E1.setText("E1");
        getContentPane().add(E1);
        E1.setBounds(60, 320, 50, 23);

        E2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        E2.setText("E2");
        getContentPane().add(E2);
        E2.setBounds(120, 320, 50, 23);

        E3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        E3.setText("E3");
        getContentPane().add(E3);
        E3.setBounds(180, 320, 50, 23);

        E4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        E4.setText("E4");
        getContentPane().add(E4);
        E4.setBounds(240, 320, 50, 23);

        E5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        E5.setText("E5");
        getContentPane().add(E5);
        E5.setBounds(300, 320, 50, 23);

        E6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        E6.setText("E6");
        getContentPane().add(E6);
        E6.setBounds(360, 320, 50, 23);

        E7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        E7.setText("E7");
        getContentPane().add(E7);
        E7.setBounds(420, 320, 50, 23);

        F1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        F1.setText("F1");
        getContentPane().add(F1);
        F1.setBounds(60, 350, 50, 23);

        F2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        F2.setText("F2");
        getContentPane().add(F2);
        F2.setBounds(120, 350, 50, 23);

        F3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        F3.setText("F3");
        getContentPane().add(F3);
        F3.setBounds(180, 350, 50, 23);

        F4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        F4.setText("F4");
        F4.addActionListener(this::F4ActionPerformed);
        getContentPane().add(F4);
        F4.setBounds(240, 350, 50, 23);

        F5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        F5.setText("F5");
        getContentPane().add(F5);
        F5.setBounds(300, 350, 50, 23);

        F6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        F6.setText("F6");
        getContentPane().add(F6);
        F6.setBounds(360, 350, 50, 23);

        F7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        F7.setText("F7");
        getContentPane().add(F7);
        F7.setBounds(420, 350, 50, 23);
        getContentPane().add(whiteColor);
        whiteColor.setBounds(30, 400, 20, 15);

        available.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        available.setText("Available");
        getContentPane().add(available);
        available.setBounds(60, 400, 60, 14);

        yellowColor.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(yellowColor);
        yellowColor.setBounds(110, 400, 20, 15);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setText("Reserved");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 400, 60, 14);

        soldColor.setBackground(new java.awt.Color(255, 51, 51));
        getContentPane().add(soldColor);
        soldColor.setBounds(190, 400, 20, 15);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setText("Sold");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 400, 20, 14);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(110, 400, 20, 15);

        greyColor.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(greyColor);
        greyColor.setBounds(250, 400, 20, 15);

        sold.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        sold.setText("Unavailable");
        getContentPane().add(sold);
        sold.setBounds(280, 400, 80, 14);

        buyTicket.setBackground(new java.awt.Color(255, 255, 153));
        buyTicket.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buyTicket.setText("BUY TICKET");
        getContentPane().add(buyTicket);
        buyTicket.setBounds(150, 500, 260, 23);

        amountLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amountLabel.setText("Amount:");
        getContentPane().add(amountLabel);
        amountLabel.setBounds(390, 430, 50, 16);

        totalAmount.setText("200");
        getContentPane().add(totalAmount);
        totalAmount.setBounds(450, 420, 100, 30);

        frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACKGROUND_PAGE.png"))); // NOI18N
        getContentPane().add(frame);
        frame.setBounds(0, 0, 590, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F4ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_A1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("SeatSelection: going back to TheaterView");
        TheaterView view = new TheaterView();
        controller.TheaterController controller = new controller.TheaterController(view);
        controller.open();
        this.dispose();
        
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> new view.SeatSelection().setVisible(true));
        
        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JLabel B;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JLabel C;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JLabel D;
    private javax.swing.JButton D1;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JLabel E;
    private javax.swing.JButton E1;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel available;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton buyTicket;
    private javax.swing.JLabel cinemaLocation;
    private javax.swing.JLabel dateTime;
    private javax.swing.JLabel frame;
    private javax.swing.JTextField greyColor;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel movieLabel;
    private javax.swing.JLabel sold;
    private javax.swing.JTextField soldColor;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JTextField whiteColor;
    private javax.swing.JTextField yellowColor;
    // End of variables declaration//GEN-END:variables

 public void AddButtonseatsListener(ActionListener Listener) {
     for (JButton btn : seats) {
         btn.addActionListener(Listener);
        }
    }



public void AddBuyTicketListener(ActionListener listener){
    buyTicket.addActionListener(listener);
}

public javax.swing.JLabel getTotalAmount(){
    return totalAmount;
}
    
    
    public javax.swing.JLabel getMovieLabel(){
        return movieLabel;
    }
}

 





