/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author DELL
 */
public class SignUp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp.class.getName());

    /**
     * Creates new form Register
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        signUp = new javax.swing.JButton();
        signIn = new javax.swing.JButton();
        mobileNumber = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        fullName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().setLayout(null);

        signUp.setBackground(new java.awt.Color(204, 204, 255));
        signUp.setText("SIGN UP");
        signUp.addActionListener(this::signUpActionPerformed);
        getContentPane().add(signUp);
        signUp.setBounds(400, 40, 80, 20);

        signIn.setBackground(new java.awt.Color(238, 242, 111));
        signIn.setText("SIGN IN");
        signIn.addActionListener(this::signInActionPerformed);
        getContentPane().add(signIn);
        signIn.setBounds(310, 40, 90, 20);

        mobileNumber.setBackground(new java.awt.Color(238, 242, 111));
        mobileNumber.setText("Enter your phone number");
        mobileNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobileNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobileNumberFocusLost(evt);
            }
        });
        mobileNumber.addActionListener(this::mobileNumberActionPerformed);
        getContentPane().add(mobileNumber);
        mobileNumber.setBounds(310, 110, 170, 30);

        email.setBackground(new java.awt.Color(238, 242, 111));
        email.setText("Enter your email");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(310, 160, 170, 30);

        fullName.setBackground(new java.awt.Color(238, 242, 111));
        fullName.setText("Enter your full name");
        fullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fullNameFocusLost(evt);
            }
        });
        fullName.addActionListener(this::fullNameActionPerformed);
        getContentPane().add(fullName);
        fullName.setBounds(310, 220, 170, 30);

        password.setBackground(new java.awt.Color(238, 242, 111));
        password.setText("PASWWORD");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(this::passwordActionPerformed);
        getContentPane().add(password);
        password.setBounds(310, 280, 170, 30);

        jLabel1.setBackground(new java.awt.Color(238, 242, 111));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Enter your password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 250, 130, 20);

        confirm.setBackground(new java.awt.Color(111, 211, 242));
        confirm.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        confirm.setText("Confirm");
        confirm.addActionListener(this::confirmActionPerformed);
        getContentPane().add(confirm);
        confirm.setBounds(370, 330, 72, 21);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 90, 140, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Email ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 150, 60, 10);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Full Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 200, 80, 16);

        cancel.setBackground(new java.awt.Color(238, 242, 111));
        cancel.setText("X");
        cancel.addActionListener(this::cancelActionPerformed);
        getContentPane().add(cancel);
        cancel.setBounds(490, 10, 50, 30);

        jLabel2.setBackground(new java.awt.Color(255, 204, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newlogo.jpg"))); // NOI18N
        jLabel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabel2FocusLost(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 560, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInActionPerformed

    private void fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void mobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNumberActionPerformed

    private void mobileNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileNumberFocusGained
        // TODO add your handling code here:
        if(mobileNumber.getText().equals("Enter your phone number")){
            mobileNumber.setText("");
        }
    }//GEN-LAST:event_mobileNumberFocusGained

    private void mobileNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileNumberFocusLost
        // TODO add your handling code here:
        if(mobileNumber.getText().equals("")){
            mobileNumber.setText("Enter your phone number");
        }
        
    }//GEN-LAST:event_mobileNumberFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("Enter your email")){
            email.setText("");
        }    
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if(email.getText().equals("")){
            email.setText("Enter your email");
        }
    }//GEN-LAST:event_emailFocusLost

    private void fullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullNameFocusGained
        // TODO add your handling code here:
        if(fullName.getText().equals("Enter your full name")){
            fullName.setText("");
        }
    }//GEN-LAST:event_fullNameFocusGained

    private void jLabel2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2FocusLost

    private void fullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullNameFocusLost
        // TODO add your handling code here:
        if(fullName.getText().equals("")){
            fullName.setText("Enter your full name");
        }
    }//GEN-LAST:event_fullNameFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if(String.valueOf(password.getPassword()).equals("Enter your password")){
        password.setText("");
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if(String.valueOf(password.getPassword()).equals("")){
        password.setText("Enter your password");
    }
    }//GEN-LAST:event_passwordFocusLost

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fullName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField mobileNumber;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signIn;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables

public void AddSignUpListener(ActionListener listener) {
        signUp.addActionListener(listener);
        
    }
public void AddSignInListener(ActionListener listener) {
        signIn.addActionListener(listener);    
    }

public void AddConfirmListener(ActionListener listener) {
        confirm.addActionListener(listener);        
    }

public void AddCancelListener(ActionListener listener) {
        cancel.addActionListener(listener);       
    }


public javax.swing.JTextField getMobileNumber() {
        return mobileNumber;    
    }

public javax.swing.JTextField getEmail() {
        return email;    
    }

public javax.swing.JTextField getFullName() {
        return fullName;    
    }

public javax.swing.JTextField getPassword() {
        return password;    
    }
}
