/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author HP
 */
public class Tereiskme_summary extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tereiskme_summary.class.getName());

    /**
     * Creates new form movie_summary
     */
    public Tereiskme_summary() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        movieName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        seatSelectionBtn = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ishqmein.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 320, 380));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel3.setText("NOW SHOWING");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 180, 50));

        movieName.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        movieName.setText("Tere Ishk Mein (2025) ");
        getContentPane().add(movieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 170, 50));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Shankar and Mukti's intense love story unfolds against the backdrop of Benaras, exploring surrender and \ntransformation through an all-consuming romance that heals, hurts, and changes them.\n\nLanguage:\nGenre: Action, Romance\nCast: DhanushKriti SanonKriti Sanon\nDirector: Aanand L. Rai");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 500, 110));

        seatSelectionBtn.setBackground(new java.awt.Color(153, 204, 255));
        seatSelectionBtn.setText("Seat Selection");
        seatSelectionBtn.addActionListener(this::seatSelectionBtnActionPerformed);
        getContentPane().add(seatSelectionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 210, -1));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACK.png"))); // NOI18N
        backButton.addActionListener(this::backButtonActionPerformed);
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACKGROUND_PAGE.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 640));

        setBounds(0, 0, 683, 644);
    }// </editor-fold>//GEN-END:initComponents

    private void seatSelectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatSelectionBtnActionPerformed
        // open seat selection and pass movie/show info
        ((javax.swing.JButton)evt.getSource()).setEnabled(false);
        System.out.println("Tereiskme_summary: opening SeatSelection");
        SeatSelection seat = new SeatSelection(this.movieName.getText(), "");
        seat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_seatSelectionBtnActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        ((javax.swing.JButton)evt.getSource()).setEnabled(false);
        TheaterView view = new TheaterView();
        controller.TheaterController controller = new controller.TheaterController(view);
        controller.open();
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tereiskme_summary().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel movieName;
    private javax.swing.JButton seatSelectionBtn;
    // End of variables declaration//GEN-END:variables

    void setVisble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public void setShowInfo(String info) {
        this.movieName.setText(info);
    }
    


}
