/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TheaterController;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author suman
 */
public class TheaterView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TheaterView.class.getName());

    

    /**
     * Creates new form TheaterView
     */
    public TheaterView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tereIshqMeinMovie = new javax.swing.JButton();
        akhandaMovie = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comingsoon = new javax.swing.JButton();
        paranMovie = new javax.swing.JButton();
        timeComboBox = new javax.swing.JComboBox<>();
        dhurandarMovie = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1500, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1500, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 1000));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel1.setText("CINEBOOK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 140, -1));

        tereIshqMeinMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tereIshqMeinMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ishqmein.png"))); // NOI18N
        tereIshqMeinMovie.setText("Tere Ishq Mein");
        tereIshqMeinMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tereIshqMeinMovie.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tereIshqMeinMovie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tereIshqMeinMovie.addActionListener(this::tereIshqMeinMovieActionPerformed);
        jPanel1.add(tereIshqMeinMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 280, 500));

        akhandaMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        akhandaMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/akhanda1.png"))); // NOI18N
        akhandaMovie.setText("Akhanda");
        akhandaMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        akhandaMovie.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        akhandaMovie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        akhandaMovie.addActionListener(this::akhandaMovieActionPerformed);
        jPanel1.add(akhandaMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, 500));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 35, 39));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Profile");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 60, 50, -1));

        comingsoon.setBackground(new java.awt.Color(204, 204, 204));
        comingsoon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comingsoon.setText("COMMING SOON\n");
        comingsoon.addActionListener(this::comingsoonActionPerformed);
        jPanel1.add(comingsoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 140, -1));

        paranMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paranMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1PARAM.png"))); // NOI18N
        paranMovie.setText("Paran");
        paranMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        paranMovie.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        paranMovie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        paranMovie.addActionListener(this::paranMovieActionPerformed);
        jPanel1.add(paranMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 280, 500));

        timeComboBox.setBackground(new java.awt.Color(204, 204, 204));
        timeComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00AM", "11:10AM", "12:30PM", "02:00PM", "03:00PM" }));
        timeComboBox.addActionListener(this::timeComboBoxActionPerformed);
        jPanel1.add(timeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 90, -1));

        dhurandarMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dhurandarMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dhurandar.png"))); // NOI18N
        dhurandarMovie.setText("Dhurandar");
        dhurandarMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dhurandarMovie.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dhurandarMovie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dhurandarMovie.addActionListener(this::dhurandarMovieActionPerformed);
        jPanel1.add(dhurandarMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 280, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACKGROUND_PAGE.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1500, 1080));
        jLabel2.setMinimumSize(new java.awt.Dimension(1500, 1080));
        jLabel2.setPreferredSize(new java.awt.Dimension(1500, 1080));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1310, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tereIshqMeinMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tereIshqMeinMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tereIshqMeinMovieActionPerformed

    private void akhandaMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akhandaMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_akhandaMovieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        profileiconview profile = new profileiconview();
        profile.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comingsoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comingsoonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        comingsoon upcoming = new comingsoon();
        upcoming.setVisible(true);
    }//GEN-LAST:event_comingsoonActionPerformed

    private void paranMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paranMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paranMovieActionPerformed

    private void timeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeComboBoxActionPerformed

    private void dhurandarMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhurandarMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dhurandarMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TheaterView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akhandaMovie;
    private javax.swing.JButton comingsoon;
    private javax.swing.JButton dhurandarMovie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton paranMovie;
    private javax.swing.JButton tereIshqMeinMovie;
    private javax.swing.JComboBox<String> timeComboBox;
    // End of variables declaration//GEN-END:variables






//public javax.swing.JTextField getPassword() {
//        return password;    
//    }
//ActionListener
//public void AddConfirmListener(ActionListener listener) {
//        confirm.addActionListener(listener);        
//    }


public void Addmov1ButtonListener(ActionListener listener){
    tereIshqMeinMovie.addActionListener(listener);
    System.out.println("Button Clicked");
         
}

public void Addmov2ButtonListener(ActionListener listener){
    akhandaMovie.addActionListener(listener);
    System.out.println("Button Clicked");
         
}

public void Addmov3ButtonListener(ActionListener listener){
    paranMovie.addActionListener(listener);
    System.out.println("Button Clicked");
}

public void Addmov4ButtonListener(ActionListener listener){
    dhurandarMovie.addActionListener(listener);
    System.out.println("Button Clicked");
}

public String getSelectedShowTime() {
    return (String) timeComboBox.getSelectedItem();
}




}

