/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TheaterController;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author suman
 */
public class TheaterView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TheaterView.class.getName());

    

    /**
     * Creates new form TheaterView
     */
    public TheaterView() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mov1Button1 = new javax.swing.JButton();
        mov1Button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 1200));

        jPanel1.setBackground(new java.awt.Color(66, 242, 245));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ticket");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 64, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Now Showing");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 105, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Cinemas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 88, -1));

        mov1Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-11 102738.png"))); // NOI18N
        mov1Button1.setText("jButton1");
        mov1Button1.addActionListener(this::mov1Button1ActionPerformed);
        jPanel1.add(mov1Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 126, 310, 425));

        mov1Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-11 080206.png"))); // NOI18N
        mov1Button2.setText("jButton1");
        mov1Button2.addActionListener(this::mov1Button2ActionPerformed);
        jPanel1.add(mov1Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mov1Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mov1Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mov1Button1ActionPerformed

    private void mov1Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mov1Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mov1Button2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        profileiconview profile = new profileiconview();
        profile.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comingsoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comingsoonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        comingsoon upcoming = new comingsoon();
        upcoming.setVisible(true);
    }//GEN-LAST:event_comingsoonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mov1Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mov1Button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mov1Button3ActionPerformed

    private void timeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeComboBoxActionPerformed

    private void mov1Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mov1Button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mov1Button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TheaterView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mov1Button1;
    private javax.swing.JButton mov1Button2;
    // End of variables declaration//GEN-END:variables






//public javax.swing.JTextField getPassword() {
//        return password;    
//    }
//ActionListener
//public void AddConfirmListener(ActionListener listener) {
//        confirm.addActionListener(listener);        
//    }


public void Addmov1ButtonListener(ActionListener listener){
    mov1Button1.addActionListener(listener);
    System.out.println("Button Clicked");
         
}

public void Addmov2ButtonListener(ActionListener listener){
    mov1Button2.addActionListener(listener);
    System.out.println("Button Clicked");
         
}




}

